
package form;
import Fungsi.JadwalFilm;
import Fungsi.Setting;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import transaksi.transaksi;
import Fungsi.Pembeli;
import Fungsi.tiket;

public class BeliTiket extends javax.swing.JFrame {
transaksi transaksi;
private ArrayList<Setting> arrset;
private ArrayList<tiket> arrtkt;
private Integer hargatotal;
Pembeli pl;
registrasi re;
String kursi;
    /**
     * Creates new form pembelian_tiket
     */
    public BeliTiket(String i, Integer x) throws SQLException {
        initComponents();
        tampil(i, x);
        this.transaksi = new transaksi();
        this.showTableJadwal();
        this.hargatotal = 0;
        this.arrset = new ArrayList<>();
        this.arrtkt = new ArrayList<>();
        this.showComboBoxJadwal();
    }

    BeliTiket() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void tampil(String i, Integer x){
        namauser.setText(i);
        idregi.setText(x.toString());
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Z2 = new javax.swing.JToggleButton();
        Z1 = new javax.swing.JToggleButton();
        Z3 = new javax.swing.JToggleButton();
        Z4 = new javax.swing.JToggleButton();
        Z5 = new javax.swing.JToggleButton();
        Z6 = new javax.swing.JToggleButton();
        Y1 = new javax.swing.JToggleButton();
        Y2 = new javax.swing.JToggleButton();
        Y3 = new javax.swing.JToggleButton();
        Y4 = new javax.swing.JToggleButton();
        Y5 = new javax.swing.JToggleButton();
        Y6 = new javax.swing.JToggleButton();
        X1 = new javax.swing.JToggleButton();
        X2 = new javax.swing.JToggleButton();
        X3 = new javax.swing.JToggleButton();
        X4 = new javax.swing.JToggleButton();
        X5 = new javax.swing.JToggleButton();
        X6 = new javax.swing.JToggleButton();
        V1 = new javax.swing.JToggleButton();
        V2 = new javax.swing.JToggleButton();
        V3 = new javax.swing.JToggleButton();
        V4 = new javax.swing.JToggleButton();
        V5 = new javax.swing.JToggleButton();
        V6 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        combotkt = new javax.swing.JComboBox<>();
        kodetiket = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        BELI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltkt = new javax.swing.JTable();

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIOSKOP");

        namauser.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        namauser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FILM");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KODE TIKET");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JUMLAH");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BANGKU");

        Z2.setBackground(new java.awt.Color(102, 102, 102));
        Z2.setText("Z2");
        Z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z2ActionPerformed(evt);
            }
        });

        Z1.setBackground(new java.awt.Color(102, 102, 102));
        Z1.setText("Z1");
        Z1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z1ActionPerformed(evt);
            }
        });

        Z3.setBackground(new java.awt.Color(102, 102, 102));
        Z3.setText("Z3");
        Z3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z3ActionPerformed(evt);
            }
        });

        Z4.setBackground(new java.awt.Color(102, 102, 102));
        Z4.setText("Z4");
        Z4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z4ActionPerformed(evt);
            }
        });

        Z5.setBackground(new java.awt.Color(102, 102, 102));
        Z5.setText("Z5");
        Z5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z5ActionPerformed(evt);
            }
        });

        Z6.setBackground(new java.awt.Color(102, 102, 102));
        Z6.setText("Z6");
        Z6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z6ActionPerformed(evt);
            }
        });

        Y1.setBackground(new java.awt.Color(102, 102, 102));
        Y1.setText("Y1");
        Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y1ActionPerformed(evt);
            }
        });

        Y2.setBackground(new java.awt.Color(102, 102, 102));
        Y2.setText("Y2");
        Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y2ActionPerformed(evt);
            }
        });

        Y3.setBackground(new java.awt.Color(102, 102, 102));
        Y3.setText("Y3");
        Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y3ActionPerformed(evt);
            }
        });

        Y4.setBackground(new java.awt.Color(102, 102, 102));
        Y4.setText("Y4");
        Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y4ActionPerformed(evt);
            }
        });

        Y5.setBackground(new java.awt.Color(102, 102, 102));
        Y5.setText("Y5");
        Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y5ActionPerformed(evt);
            }
        });

        Y6.setBackground(new java.awt.Color(102, 102, 102));
        Y6.setText("Y6");
        Y6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y6ActionPerformed(evt);
            }
        });

        X1.setBackground(new java.awt.Color(102, 102, 102));
        X1.setText("X1");
        X1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X1ActionPerformed(evt);
            }
        });

        X2.setBackground(new java.awt.Color(102, 102, 102));
        X2.setText("X2");
        X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X2ActionPerformed(evt);
            }
        });

        X3.setBackground(new java.awt.Color(102, 102, 102));
        X3.setText("X3");
        X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X3ActionPerformed(evt);
            }
        });

        X4.setBackground(new java.awt.Color(102, 102, 102));
        X4.setText("X4");
        X4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X4ActionPerformed(evt);
            }
        });

        X5.setBackground(new java.awt.Color(102, 102, 102));
        X5.setText("X5");
        X5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X5ActionPerformed(evt);
            }
        });

        X6.setBackground(new java.awt.Color(102, 102, 102));
        X6.setText("X6");
        X6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X6ActionPerformed(evt);
            }
        });

        V1.setBackground(new java.awt.Color(102, 102, 102));
        V1.setText("V1");
        V1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V1ActionPerformed(evt);
            }
        });

        V2.setBackground(new java.awt.Color(102, 102, 102));
        V2.setText("V2");
        V2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V2ActionPerformed(evt);
            }
        });

        V3.setBackground(new java.awt.Color(102, 102, 102));
        V3.setText("V3");
        V3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V3ActionPerformed(evt);
            }
        });

        V4.setBackground(new java.awt.Color(102, 102, 102));
        V4.setText("V4");
        V4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V4ActionPerformed(evt);
            }
        });

        V5.setBackground(new java.awt.Color(102, 102, 102));
        V5.setText("V5");
        V5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V5ActionPerformed(evt);
            }
        });

        V6.setBackground(new java.awt.Color(102, 102, 102));
        V6.setText("V6");
        V6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        combotkt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        kembali.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("Kembali Ke Login");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });

        BELI.setBackground(new java.awt.Color(102, 102, 102));
        BELI.setForeground(new java.awt.Color(255, 255, 255));
        BELI.setText("BELI DAN CETAK");
        BELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BELIActionPerformed(evt);
            }
        });

        idregi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BIOSKOP");

        tbltkt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane3.setViewportView(tbltkt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namauser, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(idregi))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combotkt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodetiket, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Z1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Z2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Z3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(V1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(V2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(V3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(X1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Y1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Y2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Y3)))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(V4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(V5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(V6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(X4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Y4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Y5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Y6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Z4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Z5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Z6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BELI)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(namauser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idregi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kembali)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combotkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kodetiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(V1)
                                    .addComponent(V2)
                                    .addComponent(V3)
                                    .addComponent(V4)
                                    .addComponent(V5)
                                    .addComponent(V6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(X1)
                                    .addComponent(X2)
                                    .addComponent(X3)
                                    .addComponent(X4)
                                    .addComponent(X5)
                                    .addComponent(X6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Y1)
                                    .addComponent(Y2)
                                    .addComponent(Y3)
                                    .addComponent(Y4)
                                    .addComponent(Y5)
                                    .addComponent(Y6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Z2)
                                    .addComponent(Z1)
                                    .addComponent(Z3)
                                    .addComponent(Z4)
                                    .addComponent(Z5)
                                    .addComponent(Z6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BELI)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public void showtablejad()throws SQLException{
//        DefaultTableModel tbljdw = new DefaultTableModel(new String[]{
//            "kode jadwal", "nama film", "jam tayang", "tanggal tayang", "ruang"
//        },0);
//        tbljdw.setRowCount(0);
//        for (JadwalFilm jdw : this.transaksi.getDataJadwal()) {
//            tbljdw.addRow(new String[]{
//                jdw.getkodeljadwal().toString(),
//                jdw.getfilm().genamafilm(),
//                jdw.getjam(),
//                jdw.gettgl().toString(),
//                jdw.getruang()
//            });
//            this.tbltkt.setModel(tbljdw);
//        }
//    }
        private void showTableJadwal() throws SQLException {
        DefaultTableModel dtmJadwal = new DefaultTableModel(new String[]{
            "kode jadwal", "nama film", "jam tayang", "tanggal tayang", "ruang"
        }, 0);
        dtmJadwal.setRowCount(0);

        for (JadwalFilm jdw : this.transaksi.getDataJadwal()) {
            dtmJadwal.addRow(new String[]{
                jdw.getKodeTayang().toString(),
                jdw.getfilm().getNama_Film(),
                jdw.getjam(),
                jdw.gettgl().toString(),
                jdw.getruang()
            });
        }
        this.tbltkt.setModel(dtmJadwal);
    }
        private void showComboBoxJadwal() throws SQLException {
        DefaultComboBoxModel dcbmJadwal = new DefaultComboBoxModel();

        for (JadwalFilm jd : this.transaksi.getDataJadwal()) {
            dcbmJadwal.addElement(jd.getKodeTayang().toString() + "||" + jd.getfilm().getNama_Film());
        }
        this.combotkt.setModel(dcbmJadwal);

    }
        public void fungsihave(){
            Setting sett = new Setting();
            try {
                sett.setjdwl(this.transaksi.getDataJadwal().get(combotkt.getSelectedIndex()));
                this.arrset.add(sett);
            } catch (SQLException ex) {
                Logger.getLogger(BeliTiket.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    private void dataset()
    {
        try {
            tiket tkt = new tiket();
            Setting sett = new Setting();
            sett.setjdwl(this.transaksi.getDataJadwal().get(combotkt.getSelectedIndex()));
            this.hargatotal += (this.transaksi.getDataJadwal().get(combotkt.getSelectedIndex()).getfilm().getHarga()* Integer.parseInt(jumlah.getText()));
            tkt.setTotal(this.hargatotal);

            this.arrtkt.add(tkt);
        } catch (SQLException ex) {
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X3ActionPerformed
        // TODO add your handling code here:
        kursi = X3.getText();
    }//GEN-LAST:event_X3ActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
    try {
        // TODO add your handling code here:
        new  LoginPembeli().setVisible(true);
        setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(BeliTiket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_kembaliMouseClicked
    
    public void jadwall(){
        
    }
    private void BELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BELIActionPerformed
    tiket trans = new tiket();
        try {
        // TODO add your handling code here:
        
        this.dataset();
        this.fungsihave();
        trans.setPel(this.transaksi.get_regis().get(Integer.parseInt(idregi.getText())-1));
        System.out.println(idregi.getText());
        trans.setKode_Tiket(Integer.parseInt(kodetiket.getText()));
        trans.setBanyak(Integer.parseInt(jumlah.getText()));
        trans.setarrHave(arrset);
        trans.setDuduk(kursi);
        trans.setTotal(this.hargatotal);
        this.arrtkt.add(trans);
        this.transaksi.inserttrans(trans);
        new printstruct(trans.getPel().getID()-1).show();
    } catch (SQLException ex) {
        Logger.getLogger(BeliTiket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BELIActionPerformed

    private void Z1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z1ActionPerformed
        // TODO add your handling code here:
            Z1.setBackground(new Color(204,0,0));
            kursi = Z1.getText();
    }//GEN-LAST:event_Z1ActionPerformed

    private void Z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z2ActionPerformed
        // TODO add your handling code here:
         kursi = Z2.getText();
    }//GEN-LAST:event_Z2ActionPerformed

    private void Z3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z3ActionPerformed
        // TODO add your handling code here:
         kursi = Z3.getText();
    }//GEN-LAST:event_Z3ActionPerformed

    private void Z4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z4ActionPerformed
        // TODO add your handling code here:
         kursi = Z4.getText();
    }//GEN-LAST:event_Z4ActionPerformed

    private void Z5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z5ActionPerformed
        // TODO add your handling code here:
         kursi = Z5.getText();
    }//GEN-LAST:event_Z5ActionPerformed

    private void Z6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z6ActionPerformed
        // TODO add your handling code here:
         kursi = Z6.getText();
    }//GEN-LAST:event_Z6ActionPerformed

    private void Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y1ActionPerformed
        // TODO add your handling code here:
         kursi = Y1.getText();
    }//GEN-LAST:event_Y1ActionPerformed

    private void Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y2ActionPerformed
        // TODO add your handling code here:
         kursi = Y2.getText();
    }//GEN-LAST:event_Y2ActionPerformed

    private void Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y3ActionPerformed
        // TODO add your handling code here:
         kursi = Y3.getText();
    }//GEN-LAST:event_Y3ActionPerformed

    private void Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y4ActionPerformed
        // TODO add your handling code here:
         kursi = Y4.getText();
    }//GEN-LAST:event_Y4ActionPerformed

    private void Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y5ActionPerformed
        // TODO add your handling code here:
         kursi = Y5.getText();
    }//GEN-LAST:event_Y5ActionPerformed

    private void Y6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y6ActionPerformed
        // TODO add your handling code here:
         kursi = Y6.getText();
    }//GEN-LAST:event_Y6ActionPerformed

    private void X1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X1ActionPerformed
        // TODO add your handling code here:
         kursi = X1.getText();
    }//GEN-LAST:event_X1ActionPerformed

    private void X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X2ActionPerformed
        // TODO add your handling code here:
        kursi = X2.getText();
    }//GEN-LAST:event_X2ActionPerformed

    private void X4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X4ActionPerformed
        // TODO add your handling code here:
        kursi = X4.getText();
    }//GEN-LAST:event_X4ActionPerformed

    private void X5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X5ActionPerformed
        // TODO add your handling code here:
        kursi = X5.getText();
    }//GEN-LAST:event_X5ActionPerformed

    private void X6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X6ActionPerformed
        // TODO add your handling code here:
        kursi = X6.getText();
    }//GEN-LAST:event_X6ActionPerformed

    private void V1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V1ActionPerformed
        // TODO add your handling code here:
        kursi = V1.getText();
    }//GEN-LAST:event_V1ActionPerformed

    private void V2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V2ActionPerformed
        // TODO add your handling code here:
        kursi = V2.getText();
    }//GEN-LAST:event_V2ActionPerformed

    private void V3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V3ActionPerformed
        // TODO add your handling code here:
        kursi = V3.getText();
    }//GEN-LAST:event_V3ActionPerformed

    private void V4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V4ActionPerformed
        // TODO add your handling code here:
        kursi = V4.getText();
    }//GEN-LAST:event_V4ActionPerformed

    private void V5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V5ActionPerformed
        // TODO add your handling code here:
        kursi = V5.getText();
    }//GEN-LAST:event_V5ActionPerformed

    private void V6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V6ActionPerformed
        // TODO add your handling code here:
        kursi = V6.getText();
    }//GEN-LAST:event_V6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BeliTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BELI;
    private javax.swing.JToggleButton V1;
    private javax.swing.JToggleButton V2;
    private javax.swing.JToggleButton V3;
    private javax.swing.JToggleButton V4;
    private javax.swing.JToggleButton V5;
    private javax.swing.JToggleButton V6;
    private javax.swing.JToggleButton X1;
    private javax.swing.JToggleButton X2;
    private javax.swing.JToggleButton X3;
    private javax.swing.JToggleButton X4;
    private javax.swing.JToggleButton X5;
    private javax.swing.JToggleButton X6;
    private javax.swing.JToggleButton Y1;
    private javax.swing.JToggleButton Y2;
    private javax.swing.JToggleButton Y3;
    private javax.swing.JToggleButton Y4;
    private javax.swing.JToggleButton Y5;
    private javax.swing.JToggleButton Y6;
    private javax.swing.JToggleButton Z1;
    private javax.swing.JToggleButton Z2;
    private javax.swing.JToggleButton Z3;
    private javax.swing.JToggleButton Z4;
    private javax.swing.JToggleButton Z5;
    private javax.swing.JToggleButton Z6;
    private javax.swing.JComboBox<String> combotkt;
    public static final javax.swing.JTextField idregi = new javax.swing.JTextField();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JLabel kembali;
    private javax.swing.JTextField kodetiket;
    public static final javax.swing.JTextField namauser = new javax.swing.JTextField();
    private javax.swing.JTable tbltkt;
    // End of variables declaration//GEN-END:variables
}
